// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GetAsessmentAnswers.Models;

public partial class AssessmentOption
{
    public int option_id { get; set; }

    public int? question_id { get; set; }

    public string option_text { get; set; }

    public bool? is_correct { get; set; }

    public virtual AssessmentQuestion question { get; set; }
}