// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GetAsessmentAnswers.Models;

public partial class AssessmentQuestionsRelation
{
    public int relation_id { get; set; }

    public int? parent_question_id { get; set; }

    public int? child_question_id { get; set; }

    public string relation_type { get; set; }

    public virtual AssessmentQuestion child_question { get; set; }

    public virtual AssessmentQuestion parent_question { get; set; }
}