// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GetAsessmentAnswers.Models;

public partial class AssessmentQuestion
{
    public int question_id { get; set; }

    public int? assessment_id { get; set; }

    public string question_type { get; set; }

    public string question_text { get; set; }

    public virtual ICollection<AssessmentAnswer> AssessmentAnswers { get; set; } = new List<AssessmentAnswer>();

    public virtual ICollection<AssessmentMatch> AssessmentMatches { get; set; } = new List<AssessmentMatch>();

    public virtual ICollection<AssessmentOption> AssessmentOptions { get; set; } = new List<AssessmentOption>();

    public virtual ICollection<AssessmentQuestionsRelation> AssessmentQuestionsRelationchild_questions { get; set; } = new List<AssessmentQuestionsRelation>();

    public virtual ICollection<AssessmentQuestionsRelation> AssessmentQuestionsRelationparent_questions { get; set; } = new List<AssessmentQuestionsRelation>();

    public virtual ICollection<AssessmentText> AssessmentTexts { get; set; } = new List<AssessmentText>();

    public virtual ICollection<AssessmentTrueFalse> AssessmentTrueFalses { get; set; } = new List<AssessmentTrueFalse>();

    public virtual Assessment assessment { get; set; }
}