// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GetAsessmentAnswers.Models;

public partial class AssessmentAnswer
{
    public int answer_id { get; set; }

    public int? userid { get; set; }

    public int? question_id { get; set; }

    public string user_response { get; set; }

    public bool? is_correct { get; set; }

    public virtual AssessmentQuestion question { get; set; }

    public virtual User user { get; set; }
}