// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GetAsessmentAnswers.Models;

public partial class assessment_question
{
    public long id { get; set; }

    public string question { get; set; }

    public long category_id { get; set; }

    public int level { get; set; }

    public int order { get; set; }

    public string type { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? updated_at { get; set; }

    public virtual ICollection<assessment_answer> assessment_answers { get; set; } = new List<assessment_answer>();

    public virtual ICollection<assessment_match> assessment_matches { get; set; } = new List<assessment_match>();

    public virtual ICollection<assessment_option> assessment_options { get; set; } = new List<assessment_option>();

    public virtual ICollection<assessment_questions_relation> assessment_questions_relations { get; set; } = new List<assessment_questions_relation>();

    public virtual ICollection<assessment_text> assessment_texts { get; set; } = new List<assessment_text>();

    public virtual ICollection<assessment_true_false> assessment_true_falses { get; set; } = new List<assessment_true_false>();
}