// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GetAsessmentAnswers.Models;

public partial class AssessmentsContext : DbContext
{
    public AssessmentsContext(DbContextOptions<AssessmentsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assessment> Assessments { get; set; }

    public virtual DbSet<AssessmentAnswer> AssessmentAnswers { get; set; }

    public virtual DbSet<AssessmentEnrol> AssessmentEnrols { get; set; }

    public virtual DbSet<AssessmentMatch> AssessmentMatches { get; set; }

    public virtual DbSet<AssessmentOption> AssessmentOptions { get; set; }

    public virtual DbSet<AssessmentQuestion> AssessmentQuestions { get; set; }

    public virtual DbSet<AssessmentQuestionsRelation> AssessmentQuestionsRelations { get; set; }

    public virtual DbSet<AssessmentText> AssessmentTexts { get; set; }

    public virtual DbSet<AssessmentTrueFalse> AssessmentTrueFalses { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Assessment>(entity =>
        {
            entity.HasKey(e => e.assessment_id).HasName("PK__Assessme__00B98C265C9D7E88");

            entity.Property(e => e.title).HasMaxLength(255);
        });

        modelBuilder.Entity<AssessmentAnswer>(entity =>
        {
            entity.HasKey(e => e.answer_id).HasName("PK__Assessme__33724318595387DF");

            entity.HasOne(d => d.question).WithMany(p => p.AssessmentAnswers)
                .HasForeignKey(d => d.question_id)
                .HasConstraintName("FK__Assessmen__quest__5812160E");

            entity.HasOne(d => d.user).WithMany(p => p.AssessmentAnswers)
                .HasForeignKey(d => d.userid)
                .HasConstraintName("FK__Assessmen__useri__571DF1D5");
        });

        modelBuilder.Entity<AssessmentEnrol>(entity =>
        {
            entity.HasKey(e => e.enrol_id).HasName("PK__Assessme__167C5B8F629E3F58");

            entity.Property(e => e.enrolment_date).HasColumnType("datetime");

            entity.HasOne(d => d.assessment).WithMany(p => p.AssessmentEnrols)
                .HasForeignKey(d => d.assessment_id)
                .HasConstraintName("FK__Assessmen__asses__37A5467C");

            entity.HasOne(d => d.user).WithMany(p => p.AssessmentEnrols)
                .HasForeignKey(d => d.userid)
                .HasConstraintName("FK__Assessmen__useri__36B12243");
        });

        modelBuilder.Entity<AssessmentMatch>(entity =>
        {
            entity.HasKey(e => e.match_id).HasName("PK__Assessme__9D7FCBA37BD176EC");

            entity.ToTable("AssessmentMatch");

            entity.HasOne(d => d.question).WithMany(p => p.AssessmentMatches)
                .HasForeignKey(d => d.question_id)
                .HasConstraintName("FK__Assessmen__quest__4BAC3F29");
        });

        modelBuilder.Entity<AssessmentOption>(entity =>
        {
            entity.HasKey(e => e.option_id).HasName("PK__Assessme__F4EACE1B5ACA38A7");

            entity.HasOne(d => d.question).WithMany(p => p.AssessmentOptions)
                .HasForeignKey(d => d.question_id)
                .HasConstraintName("FK__Assessmen__quest__4E88ABD4");
        });

        modelBuilder.Entity<AssessmentQuestion>(entity =>
        {
            entity.HasKey(e => e.question_id).HasName("PK__Assessme__2EC215492541BCDE");

            entity.Property(e => e.question_type).HasMaxLength(50);

            entity.HasOne(d => d.assessment).WithMany(p => p.AssessmentQuestions)
                .HasForeignKey(d => d.assessment_id)
                .HasConstraintName("FK__Assessmen__asses__44FF419A");
        });

        modelBuilder.Entity<AssessmentQuestionsRelation>(entity =>
        {
            entity.HasKey(e => e.relation_id).HasName("PK__Assessme__C409F323D3882872");

            entity.ToTable("AssessmentQuestionsRelation");

            entity.Property(e => e.relation_type).HasMaxLength(50);

            entity.HasOne(d => d.child_question).WithMany(p => p.AssessmentQuestionsRelationchild_questions)
                .HasForeignKey(d => d.child_question_id)
                .HasConstraintName("FK__Assessmen__child__48CFD27E");

            entity.HasOne(d => d.parent_question).WithMany(p => p.AssessmentQuestionsRelationparent_questions)
                .HasForeignKey(d => d.parent_question_id)
                .HasConstraintName("FK__Assessmen__paren__47DBAE45");
        });

        modelBuilder.Entity<AssessmentText>(entity =>
        {
            entity.HasKey(e => e.text_id).HasName("PK__Assessme__E2597D5FA60116FD");

            entity.ToTable("AssessmentText");

            entity.HasOne(d => d.question).WithMany(p => p.AssessmentTexts)
                .HasForeignKey(d => d.question_id)
                .HasConstraintName("FK__Assessmen__quest__5165187F");
        });

        modelBuilder.Entity<AssessmentTrueFalse>(entity =>
        {
            entity.HasKey(e => e.true_false_id).HasName("PK__Assessme__8A9FAFD0B094A75E");

            entity.ToTable("AssessmentTrueFalse");

            entity.HasOne(d => d.question).WithMany(p => p.AssessmentTrueFalses)
                .HasForeignKey(d => d.question_id)
                .HasConstraintName("FK__Assessmen__quest__5441852A");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.userid).HasName("PK__Users__CBA1B2573902473C");

            entity.Property(e => e.email).HasMaxLength(255);
            entity.Property(e => e.password).HasMaxLength(255);
            entity.Property(e => e.username).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}