// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GetAsessmentAnswers.Models;

public partial class Assessment
{
    public int assessment_id { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public virtual ICollection<AssessmentEnrol> AssessmentEnrols { get; set; } = new List<AssessmentEnrol>();

    public virtual ICollection<AssessmentQuestion> AssessmentQuestions { get; set; } = new List<AssessmentQuestion>();
}