// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GetAsessmentAnswers.Models;

public partial class User
{
    public int userid { get; set; }

    public string username { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public virtual ICollection<AssessmentAnswer> AssessmentAnswers { get; set; } = new List<AssessmentAnswer>();

    public virtual ICollection<AssessmentEnrol> AssessmentEnrols { get; set; } = new List<AssessmentEnrol>();
}